const fs=require('fs');
function ok(name,cond){if(!cond){console.error('  ✘ '+name);process.exit(1);}console.log('  ✔ '+name);}
const code=fs.readFileSync('cloudflare_sync_patch.js','utf8');
const html=fs.readFileSync('index.html','utf8');
const manifest=JSON.parse(fs.readFileSync('bundle-manifest.json','utf8'));
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
console.log('== CLOUDFLARE SYNC UI ==');
ok('usa endpoint workers.dev correto',/digicopy-sync-api\.kauangabrielcardososilva7890\.workers\.dev/.test(code));
ok('token individual fica em chave local própria',/digicopy_cloud_device_token_v1/.test(code));
ok('segredo não é salvo no localStorage',!/setItem\([^\n]*secret/i.test(code));
ok('possui primeiro setup, convite, ingresso e recuperação',/\/v1\/setup/.test(code)&&/\/v1\/invites/.test(code)&&/\/v1\/enroll/.test(code)&&/\/v1\/recover/.test(code));
ok('botão Nuvem está na barra superior',/id="btn-nuvem"[^>]*abrirCloudflareNuvem/.test(html));
ok('Nuvem aparece antes de autorizar e depois fica só para Admin',/needsAuthorization=!token\(\)/.test(code)&&/admin\|\|needsAuthorization/.test(code));
ok('Backup fica sempre só para Admin',/backup\.style\.display=admin/.test(code));
ok('acesso direto pós-autorização é bloqueado para não-Admin',/!systemAdmin\(\)&&token\(\)/.test(code));
ok('token revogado libera nova autorização',/forgetAuth/.test(code)&&/refreshVisibility/.test(code));
ok('exportação também valida Admin',/Somente o administrador pode exportar/.test(code));
ok('painel compara clientes locais e nuvem',/CLIENTES NESTE PC/.test(code)&&/CLIENTES NA NUVEM/.test(code));
ok('admin mantém somente aparelhos e excluídos',/dc-list-deleted/.test(code)&&/dc-list-devices/.test(code));
ok('ferramentas temporárias saíram da interface',!/dc-dedupe-clients|dc-review-blocked|dc-reset-cloud|dc-clear-tests/.test(code));
ok('aparelhos mostram registros, alterações e último acesso',/activeRecords/.test(code)&&/totalChanges/.test(code)&&/Último acesso/.test(code));
ok('publicação manual continua disponível quando pausada',/Publicar este PC na nuvem/.test(code));
ok('restaura e bloqueia com confirmação',/\/v1\/restore/.test(code)&&/\/v1\/devices\/revoke/.test(code));
ok('novo painel está no bundle',manifest.includes('cloudflare_sync_patch.js'));
ok('Firebase automático não é mais carregado',!manifest.includes('sync_realtime_patch.js'));
ok('gatilho antigo de carga automática é travado',/digicopy_auto_load_try_v4939/.test(code) && /syncCarregarDaNuvem=async function\(\)/.test(code));
ok('diagnóstico Firebase antigo não é carregado',!manifest.includes('ajustes_v52025_patch.js'));
ok('arquivo entra no build Electron',pkg.build.files.includes('app.bundle.js') && manifest.includes('cloudflare_sync_patch.js'));
console.log('\nRESULTADO: interface Cloudflare passou!');
