const fs = require('fs');
function ok(name, cond){ if(!cond){ console.error('  ✘ '+name); process.exit(1); } console.log('  ✔ '+name); }
const code=fs.readFileSync('sequencias_legado_patch.js','utf8');
const db={config:{seq:{cliente_emp:10,venda_emp:20000}}, clientes:[]};
const ctx={window:{}, db};
new Function('window','db',code)(ctx.window,ctx.db);
const S=ctx.window.SEQUENCIAS_LEGADO_PURE;
console.log('== SEQUENCIAS_LEGADO_PURE ==');
ok('carregou último valor de venda antigo', S.SEQUENCIAS_LEGADO.GEN_VENDAS_ID===16932);
ok('mapeia cliente', S.TIPO_POR_GENERATOR.GEN_CLIENTES_ID==='cliente');
ok('extrai último número simples', S.codigo('VD-2026-00081')===81);
ok('baseline venda', S.baselineTipo('venda')===16932);
ok('próximo usa baseline se lista menor', S.proximoComBaseline('cliente', [{codigo:5}], 'emp', x=>x.codigo)===2594);
ok('próximo usa lista se lista maior', S.proximoComBaseline('venda', [{numero:20000}], 'emp', x=>x.numero)===20001);
const changed=S.aplicarSequenciasLegado(db,'emp');
ok('aplicou sequências', changed>0);
ok('não reduz sequência já maior', db.config.seq.venda_emp===20000);
ok('sobe sequência menor para último legado', db.config.seq.cliente_emp===2593 && db.config.seq.os_emp===6304);
ok('preserva tabela de sequências', db.config.sequenciasLegado.GEN_CONTAS_RECEBER_ID===18201);
console.log('\nRESULTADO: Testes de sequências legadas passaram!');
