const fs=require('fs');
function ok(name,cond){if(!cond){console.error('  ✘ '+name);process.exit(1);}console.log('  ✔ '+name);}
const code=fs.readFileSync('cloudflare_sync_patch.js','utf8');
const html=fs.readFileSync('index.html','utf8');
const manifest=JSON.parse(fs.readFileSync('bundle-manifest.json','utf8'));
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
console.log('== CLOUDFLARE SYNC UI ==');
ok("usa endpoint workers.dev correto (v5.24.34: ele confirmou QUER o gratis — subdominio digicopyonline definitivo; nome de vendas fica pra dominio proprio depois)",/digicopy-sync-api\.digicopyonline\.workers\.dev/.test(code));
ok('token individual fica em chave local própria',/digicopy_cloud_device_token_v1/.test(code));
ok('segredo não é salvo no localStorage',!/setItem\([^\n]*secret/i.test(code));
ok('possui primeiro setup, convite, ingresso e recuperação',/\/v1\/setup/.test(code)&&/\/v1\/invites/.test(code)&&/\/v1\/enroll/.test(code)&&/\/v1\/recover/.test(code));
ok('botão Nuvem está na barra superior',/id="btn-nuvem"[^>]*abrirCloudflareNuvem/.test(html));
ok('Nuvem aparece para TODO PC (v6.0.6: o papel blinda o conteúdo, não o botão)',/if\(cloud\)cloud\.style\.display='';/.test(code));
ok('Backup fica sempre só para Admin',/backup\.style\.display=admin/.test(code));
ok('Dono também gerencia a nuvem (entra como admin)',/p==='admin'\|\|p==='dono'/.test(code));
ok('gastos e zona de admin trancados pelo PAPEL DO APARELHO (v6.0.6: PC comum só desconecta a si)',/d\.role==='admin'/.test(code)&&code.indexOf("(isAdmin?usoBloco:'')")>=0&&code.indexOf('Desconectar ESTE computador')>=0);
ok('token revogado libera nova autorização',/forgetAuth/.test(code)&&/refreshVisibility/.test(code));
ok('exportação também valida Admin',/Somente o administrador pode exportar/.test(code));
ok('painel compara clientes locais e nuvem',/CLIENTES NESTE PC/.test(code)&&/CLIENTES NA NUVEM/.test(code));
ok('admin mantém somente aparelhos e excluídos',/dc-list-deleted/.test(code)&&/dc-list-devices/.test(code));
ok('ferramentas temporárias saíram da interface',!/dc-dedupe-clients|dc-review-blocked|dc-clear-tests/.test(code));
ok('admin pode zerar a nuvem e depois escolher o que enviar',/dc-reset-cloud/.test(code)&&/resetCloudOnly/.test(code)&&/dc-enviar-locais/.test(code));
ok('aparelhos mostram registros, alterações e último acesso',/activeRecords/.test(code)&&/totalChanges/.test(code)&&/Último acesso/.test(code));
ok('escolha aparece quando a sincronização está parada',/const escolher=!!sync\.paused/.test(code));
ok('nada sobe sem a pessoa escolher',/dc-enviar-locais/.test(code)&&/dc-nao-enviar/.test(code));
ok('explica que não duplica',/não duplicar/.test(code));
ok('restaura e bloqueia com confirmação',/\/v1\/restore/.test(code)&&/\/v1\/devices\/revoke/.test(code));
ok('novo painel está no bundle',manifest.includes('cloudflare_sync_patch.js'));
ok('Firebase automático apagado',!fs.existsSync('sync_realtime_patch.js'));
ok('gatilho antigo de carga automática é travado',/digicopy_auto_load_try_v4939/.test(code) && /syncCarregarDaNuvem=async function\(\)/.test(code));
ok('diagnóstico Firebase antigo apagado',!fs.existsSync('ajustes_v52025_patch.js'));
ok('arquivo entra no build Electron',pkg.build.files.includes('app.bundle.js') && manifest.includes('cloudflare_sync_patch.js'));
console.log('\nRESULTADO: interface Cloudflare passou!');
